version: "3.4"

services:
  mapadobemapi:
    container_name: mapadobemapi
    image: mapadobemapi
    environment:
      - PORT=5000
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile